document.addEventListener('DOMContentLoaded', () => {
    // Basic Elements
    const ewbNum = document.getElementById('ewb-num');
    const ewbDate = document.getElementById('ewb-date');
    const ewbTransporter = document.getElementById('ewb-transporter');
    const ewbVehicle = document.getElementById('ewb-vehicle');
    const ewbMode = document.getElementById('ewb-mode');
    const ewbDistance = document.getElementById('ewb-distance');
    
    const ewbPrintContainer = document.getElementById('printable-eway-bill');

    // Removed live input binding
    // const ewbInputs = document.querySelectorAll('#eway-form input');
    // ewbInputs.forEach(inp => inp.addEventListener('input', updateEwbPreview));

    function updateEwbPreview() {
        const num = ewbNum.value || 'EWB-001';
        const date = ewbDate.value || 'N/A';
        const transporter = ewbTransporter.value || 'Transporter Name';
        const vehicle = ewbVehicle.value || 'Vehicle No';
        const mode = ewbMode.value || 'Road';
        const distance = ewbDistance.value || '0';

        // New Independent Fields
        const supName = document.getElementById('ewb-sup-name').value || 'Supplier Name';
        const supGstin = document.getElementById('ewb-sup-gstin').value || 'Supplier GSTIN';
        const buyName = document.getElementById('ewb-buy-name').value || 'Recipient Name';
        const buyGstin = document.getElementById('ewb-buy-gstin').value || 'Recipient GSTIN';
        
        const invNum = document.getElementById('ewb-inv-num').value || 'INV-000';
        const invDate = document.getElementById('ewb-inv-date').value || 'N/A';
        const goodsValue = document.getElementById('ewb-goods-value').value || '0';
        const hsn = document.getElementById('ewb-hsn').value || 'N/A';
        const num = ewbNum.value || 'EWB-001';
        const date = ewbDate.value || 'N/A';
        const transporter = ewbTransporter.value || 'Transporter Name';
        const vehicle = ewbVehicle.value || 'Vehicle No';
        const mode = ewbMode.value || 'Road';
        const distance = ewbDistance.value || '0';

        let html = `
            <div style="font-family: 'Inter', sans-serif; border: 1px solid #e2e8f0; border-radius: 12px; padding: 20px; background: #ffffff;">
                <div style="text-align: center; border-bottom: 2px solid #3b82f6; padding-bottom: 15px; margin-bottom: 20px;">
                    <h2 style="margin: 0; font-size: 24px; font-weight: 700; color: #1e293b; letter-spacing: 1px;">E-WAY BILL</h2>
                </div>

                <div style="display: flex; justify-content: space-between; align-items: flex-start; margin-bottom: 25px;">
                    <div style="color: #475569;">
                        <p style="margin: 0 0 8px;"><strong>E-Way Bill No:</strong> <span style="color: #0f172a;">${num}</span></p>
                        <p style="margin: 0 0 8px;"><strong>E-Way Bill Date:</strong> <span style="color: #0f172a;">${date}</span></p>
                        <p style="margin: 0 0 8px;"><strong>Generated By:</strong> <span style="color: #0f172a;">Supplier</span></p>
                    </div>
                    <div id="ewb-qrcode" style="width: 80px; height: 80px;"></div>
                </div>

                <div style="margin-bottom: 25px;">
                    <h4 style="background-color: #f8fafc; padding: 10px; margin: 0 0 10px; border: 1px solid #e2e8f0; border-radius: 6px; color: #3b82f6; text-transform: uppercase; font-size: 13px;">Part A - Document Details</h4>
                    <table style="width: 100%; border-collapse: collapse; font-size: 0.95em;">
                        <tbody>
                            <tr>
                                <td style="padding: 8px; border-bottom: 1px solid #e2e8f0; width: 35%; color: #64748b;">GSTIN of Supplier</td>
                                <td style="padding: 8px; border-bottom: 1px solid #e2e8f0; width: 65%; color: #0f172a;"><strong>${supGstin}</strong> (${supName})</td>
                            </tr>
                            <tr>
                                <td style="padding: 8px; border-bottom: 1px solid #e2e8f0; color: #64748b;">GSTIN of Recipient</td>
                                <td style="padding: 8px; border-bottom: 1px solid #e2e8f0; color: #0f172a;"><strong>${buyGstin}</strong> (${buyName})</td>
                            </tr>
                            <tr>
                                <td style="padding: 8px; border-bottom: 1px solid #e2e8f0; color: #64748b;">Linked Invoice No.</td>
                                <td style="padding: 8px; border-bottom: 1px solid #e2e8f0; color: #0f172a;"><strong>${invNum}</strong> (Date: ${invDate})</td>
                            </tr>
                            <tr>
                                <td style="padding: 8px; border-bottom: 1px solid #e2e8f0; color: #64748b;">Value of Goods</td>
                                <td style="padding: 8px; border-bottom: 1px solid #e2e8f0; color: #0f172a;"><strong>₹${parseFloat(goodsValue).toFixed(2)}</strong></td>
                            </tr>
                            <tr>
                                <td style="padding: 8px; border-bottom: 1px solid #e2e8f0; color: #64748b;">HSN Code</td>
                                <td style="padding: 8px; border-bottom: 1px solid #e2e8f0; color: #0f172a;"><strong>${hsn}</strong></td>
                            </tr>
                        </tbody>
                    </table>
                </div>

                <div style="margin-bottom: 20px;">
                    <h4 style="background-color: #f8fafc; padding: 10px; margin: 0 0 10px; border: 1px solid #e2e8f0; border-radius: 6px; color: #3b82f6; text-transform: uppercase; font-size: 13px;">Part B - Transport Details</h4>
                    <table style="width: 100%; border-collapse: collapse; font-size: 0.95em;">
                        <tbody>
                            <tr>
                                <td style="padding: 8px; border-bottom: 1px solid #e2e8f0; width: 35%; color: #64748b;">Transporter Name</td>
                                <td style="padding: 8px; border-bottom: 1px solid #e2e8f0; width: 65%; color: #0f172a;"><strong>${transporter}</strong></td>
                            </tr>
                            <tr>
                                <td style="padding: 8px; border-bottom: 1px solid #e2e8f0; color: #64748b;">Vehicle Number</td>
                                <td style="padding: 8px; border-bottom: 1px solid #e2e8f0; color: #0f172a;"><strong>${vehicle}</strong></td>
                            </tr>
                            <tr>
                                <td style="padding: 8px; border-bottom: 1px solid #e2e8f0; color: #64748b;">Mode of Transport</td>
                                <td style="padding: 8px; border-bottom: 1px solid #e2e8f0; color: #0f172a;"><strong>${mode}</strong></td>
                            </tr>
                            <tr>
                                <td style="padding: 8px; border-bottom: 1px solid #e2e8f0; color: #64748b;">Distance (KM)</td>
                                <td style="padding: 8px; border-bottom: 1px solid #e2e8f0; color: #0f172a;"><strong>${distance}</strong></td>
                            </tr>
                        </tbody>
                    </table>
                </div>
            </div>
        `;

        ewbPrintContainer.innerHTML = html;

        // Generate QR code
        if(window.barcodeUtils && num) {
            window.barcodeUtils.generateQR('ewb-qrcode', num);
        }
    }

    // Initialize empty preview
    setTimeout(updateEwbPreview, 100);

    // Manual Preview
    const previewBtn = document.getElementById('ewb-preview-btn');
    if (previewBtn) {
        previewBtn.addEventListener('click', () => {
            updateEwbPreview();
            
            if (window.innerWidth <= 768) {
                document.getElementById('printable-eway-bill').scrollIntoView({ behavior: 'smooth', block: 'start' });
            }
        });
    }

    // Generate PDF
    document.getElementById('ewb-generate-pdf').addEventListener('click', () => {
        const num = document.getElementById('ewb-num').value || 'EwayBill';
        const element = document.getElementById('printable-eway-bill');
        const btn = document.getElementById('ewb-generate-pdf');

        btn.innerText = "Generating PDF...";
        btn.disabled = true;

        const opt = {
            margin:       10,
            filename:     `${num}_EWay_Bill.pdf`,
            image:        { type: 'jpeg', quality: 0.98 },
            html2canvas:  { scale: 2, useCORS: true },
            jsPDF:        { unit: 'mm', format: 'a4', orientation: 'portrait' }
        };

        html2pdf().set(opt).from(element).save().then(() => {
            btn.innerText = "Export E-Way Bill PDF";
            btn.disabled = false;
        }).catch(err => {
            console.error("PDF Generation failed", err);
            alert("Failed to generate PDF. Please try again.");
            btn.innerText = "Export E-Way Bill PDF";
            btn.disabled = false;
        });
    });
});
