document.addEventListener('DOMContentLoaded', () => {
    // Basic Elements
    const ewbNum = document.getElementById('ewb-num');
    const ewbDate = document.getElementById('ewb-date');
    const ewbTransporter = document.getElementById('ewb-transporter');
    const ewbVehicle = document.getElementById('ewb-vehicle');
    const ewbMode = document.getElementById('ewb-mode');
    const ewbDistance = document.getElementById('ewb-distance');
    
    const ewbPrintContainer = document.getElementById('printable-eway-bill');

    // Inputs binding
    const ewbInputs = document.querySelectorAll('#eway-form input');
    ewbInputs.forEach(inp => inp.addEventListener('input', updateEwbPreview));

    function updateEwbPreview() {
        const num = ewbNum.value || 'EWB-001';
        const date = ewbDate.value || 'N/A';
        const transporter = ewbTransporter.value || 'Transporter Name';
        const vehicle = ewbVehicle.value || 'Vehicle No';
        const mode = ewbMode.value || 'Road';
        const distance = ewbDistance.value || '0';

        let html = `
            <div style="border: 1px solid #cbd5e1; border-radius: 8px; padding: 20px; font-family: sans-serif;">
                <div style="text-align: center; border-bottom: 2px solid #cbd5e1; padding-bottom: 15px; margin-bottom: 20px;">
                    <h2 style="margin: 0; font-size: 20px; text-transform: uppercase;">E-Way Bill</h2>
                </div>

                <div style="display: flex; justify-content: space-between; align-items: flex-start; margin-bottom: 20px;">
                    <div>
                        <p style="margin: 0 0 8px;"><strong>E-Way Bill No:</strong> ${num}</p>
                        <p style="margin: 0 0 8px;"><strong>E-Way Bill Date:</strong> ${date}</p>
                        <p style="margin: 0 0 8px;"><strong>Generated By:</strong> Supplier</p>
                    </div>
                    <div id="ewb-qrcode" style="width: 80px; height: 80px;"></div>
                </div>

                <div style="margin-bottom: 20px;">
                    <h4 style="background-color: #f1f5f9; padding: 8px; margin: 0 0 10px; border: 1px solid #cbd5e1;">Part A - Document Details</h4>
                    <table style="width: 100%; border-collapse: collapse; font-size: 0.9em;">
                        <tbody>
                            <tr>
                                <td style="padding: 6px; border: 1px solid #cbd5e1; width: 30%;">GSTIN of Supplier</td>
                                <td style="padding: 6px; border: 1px solid #cbd5e1; width: 70%;"><strong>To be linked with Invoice</strong></td>
                            </tr>
                            <tr>
                                <td style="padding: 6px; border: 1px solid #cbd5e1;">GSTIN of Recipient</td>
                                <td style="padding: 6px; border: 1px solid #cbd5e1;"><strong>To be linked with Invoice</strong></td>
                            </tr>
                            <tr>
                                <td style="padding: 6px; border: 1px solid #cbd5e1;">Value of Goods</td>
                                <td style="padding: 6px; border: 1px solid #cbd5e1;"><strong>To be linked with Invoice</strong></td>
                            </tr>
                            <tr>
                                <td style="padding: 6px; border: 1px solid #cbd5e1;">HSN Code</td>
                                <td style="padding: 6px; border: 1px solid #cbd5e1;"><strong>To be linked with Invoice</strong></td>
                            </tr>
                        </tbody>
                    </table>
                </div>

                <div style="margin-bottom: 20px;">
                    <h4 style="background-color: #f1f5f9; padding: 8px; margin: 0 0 10px; border: 1px solid #cbd5e1;">Part B - Transport Details</h4>
                    <table style="width: 100%; border-collapse: collapse; font-size: 0.9em;">
                        <tbody>
                            <tr>
                                <td style="padding: 6px; border: 1px solid #cbd5e1; width: 30%;">Transporter Name</td>
                                <td style="padding: 6px; border: 1px solid #cbd5e1; width: 70%;"><strong>${transporter}</strong></td>
                            </tr>
                            <tr>
                                <td style="padding: 6px; border: 1px solid #cbd5e1;">Vehicle Number</td>
                                <td style="padding: 6px; border: 1px solid #cbd5e1;"><strong>${vehicle}</strong></td>
                            </tr>
                            <tr>
                                <td style="padding: 6px; border: 1px solid #cbd5e1;">Mode of Transport</td>
                                <td style="padding: 6px; border: 1px solid #cbd5e1;"><strong>${mode}</strong></td>
                            </tr>
                            <tr>
                                <td style="padding: 6px; border: 1px solid #cbd5e1;">Distance (KM)</td>
                                <td style="padding: 6px; border: 1px solid #cbd5e1;"><strong>${distance}</strong></td>
                            </tr>
                        </tbody>
                    </table>
                </div>
            </div>
        `;

        ewbPrintContainer.innerHTML = html;

        // Generate QR code
        if(window.barcodeUtils && num) {
            window.barcodeUtils.generateQR('ewb-qrcode', num);
        }
    }

    // Initialize
    setTimeout(updateEwbPreview, 100);

    // Generate PDF
    document.getElementById('ewb-generate-pdf').addEventListener('click', () => {
        const titleOrig = document.title;
        const num = document.getElementById('ewb-num').value || 'EwayBill';
        document.title = `${num}_EWay_Bill`;
        window.print();
        document.title = titleOrig;
    });
});
